FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y curl

VOLUME ["/root/.ollama", "/training_model/models"]
RUN mkdir -p /training_model/models && chmod 777 /training_model/models

EXPOSE 11434

ENV OLLAMA_MODELS="/training_model/models"

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
